backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

# for local testing
# npx netlify-cms-proxy-server

local_backend: true

collections:
  - name: "tips" # Used in routes, e.g., /admin/collections/tips
    label: "Tips" # Used in the UI
    folder: "content/tips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fieldGroups:
      - {name: "inspo-ref", label: "Inspiration & Reference"}
      - {name: "content", label: "Content"}
    fields: # The fields for each document, usually in front matter
      - {label: "Subhead", name: "subhead", widget: "string", group: "content"}
      - {label: "Description", name: "desc", widget: "string", group: "content"}
      - {label: "Hero image", name: "bgImage", widget: "string", group: "content"}
      - {label: "Title", name: "title", widget: "string", group: "content"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL", group: "content"}
      - {label: "Body", name: "body", widget: "markdown", group: "content"}
      - {label: "Active", name: "active", widget: "boolean", default: true, group: "content"},
      - label: "Reference"
        name: "reference"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
