backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Tips"
    name: "tips"
    folder: "content/tips"
    slug: "{{fields.slug}}"
    create: true
    widget: "object"
    summary: '{{fields.desc}}'
    fields:
      
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "LLL"

      - label: "Slug"
        name: "slug"
        widget: "string"
        
      - label: "Active"
        name: "active"
        widget: "boolean"
        default: true

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Subhead"
        name: "subhead"
        widget: "string"

      - label: "Description"
        name: "desc"
        widget: "string"

      - label: "Hero image"
        name: "bgImage"
        widget: "image"

      # - label: "Body"
      #   name: "body"
      #   widget: "markdown"
      #   group: "content"

      # - label: "Meta"
      #   name: "meta"
      #   widget: "object"
      #   collapsed: false
      #   fields: 
      #     - label: "Publish Date"
      #       name: "date"
      #       widget: "datetime"
      #       date_format: "DD.MM.YYYY"
      #       time_format: "HH:mm"
      #       format: "LLL"


      - label: "Tip list"
        name: "tip-list"
        widget: "list"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
            group: "content"

      - label: "Reference"
        name: "reference"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}

    